<?php

namespace app\controllers;
use Yii;

class PostController extends AppController {

    public $layout = 'basic'; // установка шаблона для конролера целиком


    // метод выполняется до экшена
    public function beforeAction($action)
    {
        // отключим проверку токена если пришел на индекс
        if($action->id == 'show'){
            $this->enableCsrfValidation = false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex(){

        if(Yii::$app->request->isAjax){
            $data = Yii::$app->request->post();
        }


        $names = ['Ivanov', 'Petrov', 'Сидоров'];
        return $this->render('index', ['names' => $names]);
    }

    public function actionShow(){
        //$this->layout = 'basic'; // установка шаблона для конкретной страницы
        return $this->render('show');
    }

}